github: 
patreon: 
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
buy_me_a_coffee: mdMandoinfo
thanks_dev: 
custom: ['https://www.paypal.me/mdMandoinfo']
